arch:
    - amd64
    - ppc64le
sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  #Excluding below versions since they are not supported by ppc64le    
jobs: 
  exclude:
    - node_js: "0.10"
      arch: ppc64le
    - node_js: "0.12"
      arch: ppc64le 
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@2 && cat coverage/lcov.info | coveralls"
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#unshift"
    on_success: change
    on_failure: change
    
 
